package com.emor.dbfinal.dao;

import com.emor.dbfinal.entity.Examination;
import com.emor.dbfinal.entity.ExaminationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ExaminationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    int countByExample(ExaminationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    int deleteByExample(ExaminationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    int insert(Examination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    int insertSelective(Examination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    List<Examination> selectByExample(ExaminationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    Examination selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    int updateByExampleSelective(@Param("record") Examination record, @Param("example") ExaminationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    int updateByExample(@Param("record") Examination record, @Param("example") ExaminationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    int updateByPrimaryKeySelective(Examination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examination
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    int updateByPrimaryKey(Examination record);
}