package com.emor.dbfinal.dao;

import com.emor.dbfinal.entity.Exercise;
import com.emor.dbfinal.entity.ExerciseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;


@Repository
public interface ExerciseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    int insertSelectives(@Param("list") List<Exercise> exercises);
    int countByExample(ExerciseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    int deleteByExample(ExerciseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    int insert(Exercise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    int insertSelective(Exercise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    List<Exercise> selectByExample(ExerciseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    Exercise selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    int updateByExampleSelective(@Param("record") Exercise record, @Param("example") ExerciseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    int updateByExample(@Param("record") Exercise record, @Param("example") ExerciseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    int updateByPrimaryKeySelective(Exercise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exercise
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    int updateByPrimaryKey(Exercise record);
}