package com.emor.dbfinal.dao;

import com.emor.dbfinal.entity.TSExercise;
import com.emor.dbfinal.entity.TSExerciseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;


@Repository
public interface TSExerciseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_exercise
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    int countByExample(TSExerciseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_exercise
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    int deleteByExample(TSExerciseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_exercise
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    int insert(TSExercise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_exercise
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    int insertSelective(TSExercise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_exercise
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    List<TSExercise> selectByExample(TSExerciseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_exercise
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") TSExercise record, @Param("example") TSExerciseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_exercise
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    int updateByExample(@Param("record") TSExercise record, @Param("example") TSExerciseExample example);
}