package com.emor.dbfinal.entity;


import lombok.ToString;

@ToString
public class Examination {
    private Student student;
    private Teacher teacher;

    public Student getStudent() {
        return student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    public Teacher getTeacher() {
        return teacher;
    }

    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.id
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.tid
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.sid
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.examination_date
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    private String examinationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.score
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    private Double score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examination.course
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    private String course;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.id
     *
     * @return the value of examination.id
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.id
     *
     * @param id the value for examination.id
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.tid
     *
     * @return the value of examination.tid
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.tid
     *
     * @param tid the value for examination.tid
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.sid
     *
     * @return the value of examination.sid
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.sid
     *
     * @param sid the value for examination.sid
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.examination_date
     *
     * @return the value of examination.examination_date
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public String getExaminationDate() {
        return examinationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.examination_date
     *
     * @param examinationDate the value for examination.examination_date
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public void setExaminationDate(String examinationDate) {
        this.examinationDate = examinationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.score
     *
     * @return the value of examination.score
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.score
     *
     * @param score the value for examination.score
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examination.course
     *
     * @return the value of examination.course
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public String getCourse() {
        return course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examination.course
     *
     * @param course the value for examination.course
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public void setCourse(String course) {
        this.course = course;
    }
}