package com.emor.dbfinal.entity;


import lombok.ToString;

import java.io.Serializable;

@ToString
public class Exercise implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.id
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    private Integer id;

    private Student student;
    private Teacher teacher;

    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }

    public Teacher getTeacher() {
        return teacher;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    public Student getStudent() {
        return student;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.tid
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.sid
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.exercise_date
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    private String exerciseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.exercise_length
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    private Integer exerciseLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise.present
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    private Boolean present;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.id
     *
     * @return the value of exercise.id
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.id
     *
     * @param id the value for exercise.id
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.tid
     *
     * @return the value of exercise.tid
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.tid
     *
     * @param tid the value for exercise.tid
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.sid
     *
     * @return the value of exercise.sid
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.sid
     *
     * @param sid the value for exercise.sid
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.exercise_date
     *
     * @return the value of exercise.exercise_date
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public String getExerciseDate() {
        return exerciseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.exercise_date
     *
     * @param exerciseDate the value for exercise.exercise_date
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public void setExerciseDate(String exerciseDate) {
        this.exerciseDate = exerciseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.exercise_length
     *
     * @return the value of exercise.exercise_length
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public Integer getExerciseLength() {
        return exerciseLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.exercise_length
     *
     * @param exerciseLength the value for exercise.exercise_length
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public void setExerciseLength(Integer exerciseLength) {
        this.exerciseLength = exerciseLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise.present
     *
     * @return the value of exercise.present
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public Boolean getPresent() {
        return present;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise.present
     *
     * @param present the value for exercise.present
     *
     * @mbggenerated Tue Jun 16 11:36:12 CST 2020
     */
    public void setPresent(Boolean present) {
        this.present = present;
    }
}