package com.emor.dbfinal.entity;

import lombok.ToString;

import java.io.Serializable;

@ToString
public class Student implements Serializable {
    Teacher teacher;

    public Teacher getTeacher() {
        return teacher;
    }

    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.NAME
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sex
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.phone
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.enter_date
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    private String enterDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.vip
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    private String vip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.tid
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.graduated
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    private Boolean graduated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.NAME
     *
     * @return the value of student.NAME
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.NAME
     *
     * @param name the value for student.NAME
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sex
     *
     * @return the value of student.sex
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sex
     *
     * @param sex the value for student.sex
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.phone
     *
     * @return the value of student.phone
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.phone
     *
     * @param phone the value for student.phone
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.enter_date
     *
     * @return the value of student.enter_date
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    public String getEnterDate() {
        return enterDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.enter_date
     *
     * @param enterDate the value for student.enter_date
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    public void setEnterDate(String enterDate) {
        this.enterDate = enterDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.vip
     *
     * @return the value of student.vip
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    public String getVip() {
        return vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.vip
     *
     * @param vip the value for student.vip
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    public void setVip(String vip) {
        this.vip = vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.tid
     *
     * @return the value of student.tid
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.tid
     *
     * @param tid the value for student.tid
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.graduated
     *
     * @return the value of student.graduated
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    public Boolean getGraduated() {
        return graduated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.graduated
     *
     * @param graduated the value for student.graduated
     *
     * @mbggenerated Tue Jun 16 22:40:58 CST 2020
     */
    public void setGraduated(Boolean graduated) {
        this.graduated = graduated;
    }
}