package com.emor.dbfinal.entity;


import lombok.ToString;

import java.io.Serializable;

@ToString
public class TSExercise implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_exercise.student_name
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_exercise.teacher_name
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    private String teacherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_exercise.id
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_exercise.tid
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_exercise.sid
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_exercise.exercise_date
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    private String exerciseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_exercise.exercise_length
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    private Integer exerciseLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_exercise.present
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    private Boolean present;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_exercise.student_name
     *
     * @return the value of ts_exercise.student_name
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_exercise.student_name
     *
     * @param studentName the value for ts_exercise.student_name
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_exercise.teacher_name
     *
     * @return the value of ts_exercise.teacher_name
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_exercise.teacher_name
     *
     * @param teacherName the value for ts_exercise.teacher_name
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_exercise.id
     *
     * @return the value of ts_exercise.id
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_exercise.id
     *
     * @param id the value for ts_exercise.id
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_exercise.tid
     *
     * @return the value of ts_exercise.tid
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_exercise.tid
     *
     * @param tid the value for ts_exercise.tid
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_exercise.sid
     *
     * @return the value of ts_exercise.sid
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_exercise.sid
     *
     * @param sid the value for ts_exercise.sid
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_exercise.exercise_date
     *
     * @return the value of ts_exercise.exercise_date
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    public String getExerciseDate() {
        return exerciseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_exercise.exercise_date
     *
     * @param exerciseDate the value for ts_exercise.exercise_date
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    public void setExerciseDate(String exerciseDate) {
        this.exerciseDate = exerciseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_exercise.exercise_length
     *
     * @return the value of ts_exercise.exercise_length
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    public Integer getExerciseLength() {
        return exerciseLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_exercise.exercise_length
     *
     * @param exerciseLength the value for ts_exercise.exercise_length
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    public void setExerciseLength(Integer exerciseLength) {
        this.exerciseLength = exerciseLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_exercise.present
     *
     * @return the value of ts_exercise.present
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    public Boolean getPresent() {
        return present;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_exercise.present
     *
     * @param present the value for ts_exercise.present
     *
     * @mbggenerated Wed Jun 17 16:00:15 CST 2020
     */
    public void setPresent(Boolean present) {
        this.present = present;
    }
}