package com.emor.dbfinal.entity;


import lombok.ToString;

import java.io.Serializable;

@ToString
public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Sun Jun 14 09:01:37 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Sun Jun 14 09:01:37 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.fid
     *
     * @mbggenerated Sun Jun 14 09:01:37 CST 2020
     */
    private Integer fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.myrole
     *
     * @mbggenerated Sun Jun 14 09:01:37 CST 2020
     */
    private String myrole;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Sun Jun 14 09:01:37 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Sun Jun 14 09:01:37 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Sun Jun 14 09:01:37 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Sun Jun 14 09:01:37 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.fid
     *
     * @return the value of user.fid
     *
     * @mbggenerated Sun Jun 14 09:01:37 CST 2020
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.fid
     *
     * @param fid the value for user.fid
     *
     * @mbggenerated Sun Jun 14 09:01:37 CST 2020
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.myrole
     *
     * @return the value of user.myrole
     *
     * @mbggenerated Sun Jun 14 09:01:37 CST 2020
     */
    public String getMyrole() {
        return myrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.myrole
     *
     * @param myrole the value for user.myrole
     *
     * @mbggenerated Sun Jun 14 09:01:37 CST 2020
     */
    public void setMyrole(String myrole) {
        this.myrole = myrole;
    }
}